const path = require('path');

const config = {
  app: {
    url: 'http://127.0.0.1:7777',
    host: '127.0.0.1',
    port: 7777
  },
  googleAnalytics: '',
  storage: {
    localUploadDelay: 5,
    dir: {
      data: path.join(__dirname, 'storage', 'data'),
      webUpload: path.join(__dirname, 'storage', 'webupload'),
      localUpload: path.join(__dirname, 'storage', 'localupload'),
      autoGenerated: path.join(__dirname, 'storage', 'auto_generated')
    }
  },
  database: {
    url: 'mongodb://localhost/animeloop'
  }
};

module.exports = config;